---
new_page_extension: md
auto_deploy: false
admin_path: public/admin
webhook_url: 
sections:
- type: document
  path: src/settings/Settings.md
  label: Site Settings
- type: document
  path: src/user-content/Projects.md
  label: Projects
- type: document
  path: src/user-content/About.md
  label: About Content
upload_dir: andrew-aiello/portfolio
public_path: https://res.cloudinary.com/tinymachine/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn cms-preview
