---
label: Site Settings
hide_body: true
fields:
- type: text
  name: name
  label: name
- type: text
  name: title
  label: title
- type: field_group
  name: reel
  label: reel
  fields:
  - type: text
    name: vimeoUrl
    label: vimeoUrl
  - type: list
    name: placeholderStills
    label: placeholderStills
- type: field_group
  name: projectSettings
  label: projectSettings
  fields:
  - type: text
    name: featureProjectTypeLabel
    label: featureProjectTypeLabel
