---
label: Site Settings
hide_body: true
fields:
- type: text
  name: name
  label: Name
  config:
    required: true
- type: text
  name: title
  label: Role
  config:
    required: true
- type: field_group
  name: reel
  label: Reel Settings
  fields:
  - type: text
    name: vimeoUrl
    label: Vimeo URL
    description: "<em>Note: the site currently only works with video URLs from Vimeo
      that end with the video's ID number (e.g. </em><code><em>https://vimeo.com/manage/videos/644686119</em></code><em>)</em>"
    config:
      required: true
  - type: list
    name: placeholderStills
    label: placeholderStills
- type: field_group
  name: projectSettings
  label: Project Settings
  fields:
  - type: text
    name: featureProjectTypeLabel
    label: Feature Films Project-Type Label
    description: All feature films will show this same project type (e.g. "Feature
      Film") on project detail pages.
pages:
- src/settings/Settings.md
